Repository cloud-foundations-on-aws/cloud-foundations-templates, pull requests merged in 2023-05, with the labels that each got.

#30 fix: tf structure
  control-tower/README.md
  control-tower/controltower-cross-account-trust/README.md
  control-tower/controltower-cross-account-trust/tf-controltower-cross-account-trust/README.md
  control-tower/controltower-cross-account-trust/tf-controltower-cross-account-trust/config.tf
  control-tower/controltower-cross-account-trust/tf-controltower-cross-account-trust/main.tf
  control-tower/controltower-cross-account-trust/tf-controltower-cross-account-trust/outputs.tf
  control-tower/controltower-cross-account-trust/tf-controltower-cross-account-trust/vars.tf
Labels: type: documentation

#32 feat: tf support for logging/kms
  logging/README.md
  logging/centralized-logging-kms-key-cloudtrail/tf-centralized-logging-kms-key-cloudtrail/README.md
  logging/centralized-logging-kms-key-cloudtrail/tf-centralized-logging-kms-key-cloudtrail/config.tf
  logging/centralized-logging-kms-key-cloudtrail/tf-centralized-logging-kms-key-cloudtrail/main.tf
  logging/centralized-logging-kms-key-cloudtrail/tf-centralized-logging-kms-key-cloudtrail/outputs.tf
  logging/centralized-logging-kms-key-cloudtrail/tf-centralized-logging-kms-key-cloudtrail/vars.tf
  logging/centralized-logging-kms-key-config/tf-centralized-logging-kms-key-config/README.md
  logging/centralized-logging-kms-key-config/tf-centralized-logging-kms-key-config/config.tf
  logging/centralized-logging-kms-key-config/tf-centralized-logging-kms-key-config/main.tf
  logging/centralized-logging-kms-key-config/tf-centralized-logging-kms-key-config/outputs.tf
  logging/centralized-logging-kms-key-config/tf-centralized-logging-kms-key-config/vars.tf
Labels: type: feature

#33 feat: acceleration day custom lens
  custom-lens/README.md
  custom-lens/cf-acceleration-day-custom-lens.json
Labels: type: feature

#34 feat: cloudfoundations tracker
  trackers-and-planning/README.md
  trackers-and-planning/cloud-foundations-tracker/Cloud Foundations Tracker.xlsx
  trackers-and-planning/cloud-foundations-tracker/README.md
Labels: type: documentation, type: feature
